- label: "Grand magasin"
  value: 50
- label: "Restaurant paisible"
  value: 50
- label: "Conversation normale"
  value: 55
- label: "Frigo"
  value: 55
- label: "Marché animé"
  value: 60
- label: "Machine à coudre"
  value: 60
- label: "Télévision"
  value: 65
- label: "Machine à laver"
  value: 65
- label: "Chantier"
  value: 65
- label: "Bruit à l'intérieur d’une voiture"
  value: 65
- label: "Tondeuse / souffleur"
  value: 70
- label: "Salle de classe bruyante"
  value: 70
- label: "Aboiement"
  value: 70
