version: 2

sources:
  - name: public_workspace
    schema: public_workspace
    tables:
      - name: raw_full_schools_data
        description: "Raw data imported from schools dataset"
        columns:
          - name: amenity
            description: "Type of amenity"
          - name: name
            description: "Name of the school"
          - name: geometry
            description: "PostGIS geometry data in EPSG:2154"
