version: '3.8'

services:
  postgis:
    image: postgis/postgis:15-3.3
    container_name: diagbruit_postgis
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: diagbruit
    volumes:
      - diagbruit_postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    restart: unless-stopped

volumes:
  diagbruit_postgres_data:
