version: 2

models:
  - name: int_osm_filter
    description: "Data with only restaurants, bars and pubs"
  - name: int_osm_validate
    description: "OSM data deduplicated against noisesource_stras"
  - name: int_osm_slug
    description: "Data with added category slugs"
  - name: int_schools_filter
    description: "Data with only named schools"
  - name: int_schools_dep
    description: "Data with added department code and name columns"
  - name: int_schools_slug
    description: "Data with added category_slug 'SCH' column"
