version: 2

models:
  - name: noisesource
    description: "Regional noise sources from Strasbourg"
    columns:
      - name: name
        description: "Name of the establishment"
      - name: geometry
        description: "Geometry in EPSG:4326, type MULTIPOLYGON or POLYGON"
      - name: category_slug
        description: "Category slug for the source, either 'REST' or 'BAR'"
