version: 2

models:
  - name: int_soundclassification_multilines
    description: "Ensures all geometries are MULTILINESTRING (standardization step)"

  - name: int_soundclassification_buffered
    description: "Applies a buffer (in meters) to geometries and converts them to POLYGON in EPSG:4326"

  - name: int_soundclassification_validated
    description: "Validates geometry and provides validation information"

  - name: int_soundclassification_fixed
    description: "Repairs invalid geometries using ST_MakeValid"

  - name: int_soundclassification_fixed_clean
    description: "Disaggregates MultiPolygons after geometries have been fixed with ST_MakeValid"

  - name: int_soundclassification_with_pk
    description: "Adds a unique primary key (pk) to each disaggregated geometry row for the sound classification dataset"

  - name: int_soundclassification_merge
    description: "Aggregates lines by codeinfra, source, and sound_category. Removes extra fields and stores merged primary keys in an array."
