version: 2

models:
  - name: int_noisemap_exploded
    description: "Disaggregates MultiPolygons into individual Polygons"

  - name: int_noisemap_validated
    description: "Validates geometry and provides validation information"

  - name: int_noisemap_fixed
    description: "Repairs invalid geometries using ST_MakeValid"

  - name: int_noisemap_projected
    description: "Transforms geometries to EPSG:4326 (WGS84) coordinate system"
